apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: dev.local/mockgo-server
      context: .
      docker:
        dockerfile: build/docker/Dockerfile

deploy:
  helm:
    releases:
      - name: mockgo-server
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-server
        valuesFiles:
          - deployments/helm/minikube-values.yaml
        setValueTemplates:
          ingress.configHost: "config.{{.MINIKUBE_IP}}.nip.io"
          ingress.mockHost: "mock.{{.MINIKUBE_IP}}.nip.io"
  kustomize:
    paths:
      - deployments/kustomize/minikube

profiles:
  - name: all
  - name: statefulset
    patches:
      - op: remove
        path: "/deploy/kustomize"
  - name: knative
    patches:
      - op: remove
        path: "/deploy/helm"
