apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: dev.local/mockgo-standalone
      context: .
      docker:
        dockerfile: build/docker/mockgo-standalone.Dockerfile
    - image: dev.local/mockgo-grpc
      context: .
      docker:
        dockerfile: build/docker/mockgo-grpc.Dockerfile

deploy:
  helm:
    releases:
      - name: mockgo-standalone
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-standalone
        valuesFiles:
          - deployments/helm/minikube-standalone-values.yaml
        setValueTemplates:
          ingress.host: "mockgo-standalone.{{.MINIKUBE_IP}}.nip.io"
      - name: mockgo-grpc
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-grpc
        valuesFiles:
          - deployments/helm/minikube-grpc-values.yaml
        setValueTemplates:
          ingress.host: "mockgo-grpc.{{.MINIKUBE_IP}}.nip.io"
