apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: dev.local/mockgo-standalone
      context: mockgo-standalone
      docker:
        dockerfile: build/mockgo-standalone.Dockerfile
      hooks:
        before:
          - command: [ go, build, -C, cmd, -o, ../bin/mockgo-standalone-linux-amd64 ]
            os: [ linux ]
            dir: mockgo-standalone

    - image: dev.local/mockgo-grpc
      context: mockgo-grpc
      docker:
        dockerfile: build/mockgo-grpc.Dockerfile
      hooks:
        before:
          - command: [ go, build, -C, cmd, -o, ../bin/mockgo-grpc-linux-amd64 ]
            os: [ linux ]
            dir: mockgo-standalone

deploy:
  helm:
    releases:
      - name: mockgo-standalone
        chartPath: deployments/helm/mockgo-server
        valuesFiles:
          - deployments/helm/standalone-values.yaml
      - name: mockgo-grpc
        chartPath: deployments/helm/mockgo-server
        valuesFiles:
          - deployments/helm/grpc-values.yaml
      - name: prometheus
        remoteChart: prometheus-community/prometheus
        valuesFiles:
          - deployments/helm/prometheus-values.yaml
profiles:
  - name: standalone
    patches:
      - op: remove
        path: "/build/artifacts/1"
      - op: remove
        path: "/deploy/helm/releases/1"
  - name: cluster
    patches:
      - op: remove
        path: "/build/artifacts/0"
      - op: remove
        path: "/deploy/helm/releases/0"
