apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: dev.local/mockgo-standalone
      context: .
      docker:
        dockerfile: build/docker/mockgo-standalone.Dockerfile

deploy:
  helm:
    releases:
      - name: mockgo-server
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-standalone
        valuesFiles:
          - deployments/helm/minikube-standalone-values.yaml
        setValueTemplates:
          ingress.host: "mockgo.{{.MINIKUBE_IP}}.nip.io"
