apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: dev.local/mockgo-standalone
      context: mockgo-standalone
      docker:
        dockerfile: build/mockgo-standalone.Dockerfile
        buildArgs:
          RELEASE: testversion

    - image: dev.local/mockgo-grpc
      context: mockgo-grpc
      docker:
        dockerfile: build/mockgo-grpc.Dockerfile
        buildArgs:
          RELEASE: testversion

deploy:
  helm:
    releases:
      - name: mockgo-standalone
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-standalone
        valuesFiles:
          - deployments/helm/standalone-values.yaml
        setValueTemplates:
          ingress.host: "mockgo-standalone.{{.CLUSTER_IP}}.nip.io"
      - name: mockgo-grpc
        chartPath: deployments/helm/mockgo-server
        artifactOverrides:
          image: dev.local/mockgo-grpc
        valuesFiles:
          - deployments/helm/grpc-values.yaml
        setValueTemplates:
          ingress.host: "mockgo-grpc.{{.CLUSTER_IP}}.nip.io"
      - name: prometheus
        remoteChart: prometheus-community/prometheus
        valuesFiles:
          - deployments/helm/prometheus-values.yaml
profiles:
  - name: standalone
    patches:
      - op: remove
        path: "/build/artifacts/1"
      - op: remove
        path: "/deploy/helm/releases/1"
  - name: cluster
    patches:
      - op: remove
        path: "/build/artifacts/0"
      - op: remove
        path: "/deploy/helm/releases/0"
