apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  artifacts:
    - image: mockgo-standalone
      custom:
        buildCommand: "make pushdocker MOCKGO_MODULE=mockgo-standalone MOCKGO_RELEASE=$(git rev-parse --short HEAD)"
        dependencies:
          paths:
          - "mockgo/**"
          - "mockgo-standalone/**"
    - image: mockgo-grpc
      custom:
        buildCommand: "make pushdocker MOCKGO_MODULE=mockgo-grpc MOCKGO_RELEASE=$(git rev-parse --short HEAD)"
        dependencies:
          paths:
          - "mockgo/**"
          - "grpc-kvstore/**"
          - "grpc-matchstore/**"
          - "mockgo-grpc/**"

deploy:
  helm:
    releases:
      - name: mockgo-standalone
        chartPath: deployments/helm/mockgo-server
        valuesFiles:
          - deployments/helm/standalone-values.yaml
        setValues:
          image: mockgo-standalone
          pullPolicy: Never
      - name: mockgo-grpc
        chartPath: deployments/helm/mockgo-server
        valuesFiles:
          - deployments/helm/grpc-values.yaml
        setValues:
          image: mockgo-grpc
          pullPolicy: Never
      - name: prometheus
        remoteChart: prometheus-community/prometheus
        valuesFiles:
          - deployments/helm/prometheus-values.yaml
profiles:
  - name: standalone
    patches:
      - op: remove
        path: "/build/artifacts/1"
      - op: remove
        path: "/deploy/helm/releases/1"
      - op: remove
        path: "/deploy/helm/releases/1"
  - name: cluster
    patches:
      - op: remove
        path: "/build/artifacts/0"
      - op: remove
        path: "/deploy/helm/releases/0"
      - op: remove
        path: "/deploy/helm/releases/1"
