image: mockgo-grpc:latest
pullPolicy: Never
ingress:
  enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

cluster:
  enabled: true
  replicas: 3

api:
  password: asecretPassword

healthcheck:
  liveness:
    initialDelaySeconds: 1
  readiness:
    initialDelaySeconds: 2

logging:
  api:
    level: 2
  mock:
    level: 2

mocks:
- name: hello
  config: |
    endpoints:
    - id: hello1
      request:
        path: '/hello1'
      response:
        bodyFilename: "hello1-response.json"

responses:
- name: hello1
  type: json
  config: |
    {
      "hello": "World"
    }
