config:
  reload: true
#  read config from existing configmap
#  existingConfigmap: myconfig
#  read config from existing pvc
  # existingPVC: config

image: localhost:5001/alitari/mockgo-standalone:latest
pullPolicy: Always
ingress:
  enabled: true
  host: "mockgo-standalone.127.0.0.1.nip.io"

scraping: true

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

cluster:
  enabled: false

api:
  password: asecretPassword

healthcheck:
  liveness:
    initialDelaySeconds: 1
  readiness:
    initialDelaySeconds: 2

logging:
  api:
    level: INFO
  mock:
    level: INFO

files:
  hello-mock.yaml: |
    endpoints:
    - id: hello1
      request:
        path: '/hello1'
      response:
        bodyFilename: "hello1-response.json"
    - id: hello2
      request:
        path: '/hello2'
      response:
        headers: |
          Content-Type: "application/text"
        body: "Hello World!"
    - id: hello3
      request:
        path: '/hello3/{name}'
      response:
        headers: |
          Content-Type: "application/text"
        bodyFilename: "hello3-response.txt"
    - id: hello4
      request:
        path: '/hello4/*/{name}'
      response:
        headers: |
          Content-Type: "application/json"
        bodyFilename: "hello4-response.json"
    - id: hello5
      request:
        path: '/hello5/{name}/*'
      response:
        headers: |
          Content-Type: "application/json"
        bodyFilename: "hello4-response.json"
    - id: hello6
      request:
        path: '/hello6/{sender}/*/{receiver}'
      response:
        headers: |
          Content-Type: "application/json"
        bodyFilename: "hello6-response.json"
    - id: hello7
      request:
        path: '/hello7/{sender}/{receiver}/**'
      response:
        headers: |
          Content-Type: "application/json"
        bodyFilename: "hello6-response.json"
    - id: hello8
      request:
        path: '/hello8/**/last'
      response:
        statusCode: 202
    - id: hello9
      request:
        path: '/hello9/**/sender/{sender}/**/receiver/{receiver}'
      response:
        headers: |
          Content-Type: "application/json"
        bodyFilename: "hello6-response.json"

  hello1-response.json: |
    {
      "hello": "World"
    }
  hello3-response.txt: |
    hello, world, {{ .RequestPathParams.name }} !
  hello4-response.json: |
    {
      "message" :"Hello world, {{ .RequestPathParams.name }} !"
    }

  hello6-response.json: |
    {
      "{{ .RequestPathParams.sender }}": "says 'hello' to {{ .RequestPathParams.receiver }} !"
    }

