appVersion: v0.0.11
description: A Helm chart for mockgo-server
name: mockgo-server
keywords:
- mock
version: 0.0.3
home: https://github.com/alitari/mockgo-server
maintainers:
- name: Alexander Krieg
  url: https://github.com/alitari
  email: alitari67@gmail.com
