mocks:
- name: hello
  config: |
    endpoints:
    - request:
        path: '/hello'
      response:
        bodyFilename: "hello-response.json"

responses:
- name: hello
  type: json
  config: |
    {
      "hello": "World"
    }

logging:
  verbose: true

image: mockgo-server:1.0.0-alpine
pullPolicy: IfNotPresent

healthcheck:
  liveness:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    # Only for Kubernetes +1.22 that have pod level probes enabled.
    terminationGracePeriodSeconds:
  readiness:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3

ingress:
  enabled: false
  annotations: {}
  ingressClassName: nginx
  configHost: "confighost"
  configPath: "/"
  configPathType: Prefix
  mockHost: "mockhost"
  mockPath: "/"
  mockPathType: Prefix

# securityContext for the mockgo-server container
securityContext: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

resources: {}

configEndpoint:
  containerPort: 8080
  servicePort: 8080
mockEndpoint:
  containerPort: 8081
  servicePort: 80

nameOverride: ""
namespaceOverride: ""

# An array of imagePullSecrets, and they have to be created manually in the same namespace
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# Affinity for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Pod priority class name
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: null


# Pod Topology Spread Constraints
# ref https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
topologySpreadConstraints: []
# - maxSkew: 1
#   topologyKey: zone
#   whenUnsatisfiable: DoNotSchedule

# Annotations to add to the mockgo-server pods
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# key: "value"

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Node tolerations for server scheduling to nodes with taints
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
#
tolerations: []
#  - key: "key"
#    operator: "Equal|Exists"
#    value: "value"
#    effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

# Annotations to add to the mockgo-server StatefulSet
statefulSetAnnotations: {}

# Labels to add to the pods of the mockgo-server StatefulSet
statefulSetPodLabels: {}

cluster:
  enabled: false
  replicas: 3
  # Define if mockgo-server is using FQDN name for clustering (i.e. mockgo-server-0.mockgo-server.default.svc.cluster.local) or short name (i.e. mockgo-server-0.mockgo-server.default).
  useFQDN: true

# Cluster Domain configured on the kubelets
# https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
k8sClusterDomain: cluster.local


# Add labels to all the deployed resources
commonLabels: {}

# podManagementPolicy controls how pods are created during initial scale up,
# when replacing pods on nodes, or when scaling down.
podManagementPolicy: Parallel