apiVersion: v1
kind: ConfigMap
metadata:
  name: mockgo-server
data:
  hello-mock.yaml: |
    endpoints:
    - id: hello
      request:
        path: '/hello'
      response:
        bodyFilename: "hello-response.json"
  hello-response.json: |
    {
      "hello": "World"
    }