@port = 80
@confighost = config.192.168.67.2.nip.io
@protocol = http


### set kvstore value

PUT {{protocol}}://{{confighost}}:{{port}}/kvstore/store1
Content-Type: application/json

{
    "store1Key": "All"
}

### set kvstore value no adv

PUT {{protocol}}://{{confighost}}:{{port}}/kvstore/store1
Content-Type: application/json
No-advertise: true

{
    "store1Key": "One"
}

### get kvstore value

GET {{protocol}}://{{confighost}}:{{port}}/kvstore/store1
Accept: application/json


