{{- if not .Values.config.existingConfigmap -}}
{{- if not .Values.config.existingPVC -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mockgoserver.fullname" . }}
data:
{{- toYaml .Values.files | nindent 2 }}
{{- end }}
{{- end }}