{{- if not .Values.existingConfigmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mockgoserver.fullname" . }}
data:
{{- range .Values.files }}
{{ .name | indent 2 }}: |-
{{ .config | indent 4 }}
{{- end }}
{{- end }}
