{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mockgoserver.fullname" . -}}
{{- $svcConfigPort := .Values.configEndpoint.servicePort -}}
{{- $svcMockPort := .Values.mockEndpoint.servicePort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mockgoserver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName}}
  rules:
    - host: {{ .Values.ingress.configHost }}
      http:
        paths:
          - path: {{ .Values.ingress.configPath }}
            pathType: {{ .Values.ingress.configPathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcConfigPort }}
    - host: {{ .Values.ingress.mockHost }}
      http:
        paths:
          - path: {{ .Values.ingress.mockPath }}
            pathType: {{ .Values.ingress.mockPathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcMockPort }}

{{- end }}
