apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockgoserver.fullname" . }}
type: Opaque
data:
  apiPassword: {{ .Values.api.password | b64enc | quote }}
  {{- if .Values.redis.enabled }}
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}