apiVersion: v1
kind: Service
metadata:
  name: {{ include "mockgoserver.fullname" . }}
  namespace: {{ include "mockgoserver.namespace" . }}
  labels:
    {{- include "mockgoserver.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations}}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.cluster.enabled }}
  clusterIP: None
{{- else }}
  type: ClusterIP
{{- end }}
  selector:
    {{- include "mockgoserver.selectorLabels" . | nindent 4 }}
  ports:
  - name: service-http
    targetPort: http
    port: {{ .Values.port }}