apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mockgo-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/target: "5" # requests per replica at one time
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: mockgo-server-kn
      serviceAccountName: mockgo-server-kn