apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mockgo-server
subjects:
  - kind: ServiceAccount
    name: mockgo-server
    namespace: mockgo
roleRef:
  kind: Role
  name: mockgo-server
  apiGroup: rbac.authorization.k8s.io