name: skaffold

on:
  push:
    branches: [ "ci-skaffold" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Start Minikube
      id: minikube
      uses: hiberbee/github-action-minikube@1.7.0
      with:
        addons: ingress
    - name: Get Minikube IP
      run: echo "MINIKUBE_IP=${{ steps.minikube.outputs.ip }}" >> $GITHUB_ENV
    - name: Get cluster info
      run: kubectl cluster-info

    - name: Run Skaffold
      uses: hiberbee/github-action-skaffold@1.22.0
      with:
        command: run
    - name: Get Helm releases
      run: helm list
    - name: Show k8s resources
      run: kubectl get pod,service,statefulset,configmap,secret,ingress
    - name: Integration test precheck
      run: ./scripts/integration-test-precheck.sh


