name: OnMaster

on:
  push:
    branches: [ "master" ]
  
jobs:

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: alitari
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/Dockerfile
        push: true
        tags: alitari/mockgo-server:latest
