name: OnMaster

on:
  push:
    branches: [ "master" ]
  
jobs:


  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Test all
      run: ./scripts/go-test-all.sh
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./mockgo/cover.out,./grpc-kvstore/cover.out,./grpc-matchstore/cover.out,./mockgo-standalone/cover.out
        flags: unittests
        verbose: true

    - name: Set up docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: alitari
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build mockgo-standalone
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/mockgo-standalone.Dockerfile
        push: true
        tags: alitari/mockgo-standalone:latest

    - name: Build mockgo-grpc
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/mockgo-grpc.Dockerfile
        push: true
        tags: alitari/mockgo-grpc:latest
