name: OnPR

on:
  pull_request:
    branches: [ "master" ]

jobs:

  golang-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./scripts/go-build.sh 

    - name: Test
      run: go test -coverprofile cover.out ./...

    - name: Cover output
      run: go tool cover -func=cover.out

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/Dockerfile
        push: false
        tags: alitari/mockgo-server:latest

  acceptance-tests:
    env:
      TAVERNVER: "1.23.3"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Start Minikube
      id: minikube
      uses: hiberbee/github-action-minikube@1.7.0
      with:
        addons: ingress
    - name: Get Minikube IP
      run: echo "MINIKUBE_IP=${{ steps.minikube.outputs.ip }}" >> $GITHUB_ENV
    - name: Get cluster info
      run: kubectl cluster-info

    - name: Run Skaffold
      uses: hiberbee/github-action-skaffold@1.22.0
      with:
        command: run
    - name: Get Helm releases
      run: helm list
    - name: Show k8s resources
      run: kubectl get pod,service,statefulset,configmap,secret,ingress
    - name: Precheck environment
      run: ./scripts/integration-test-precheck.sh

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install tavern==$TAVERNVER pytest-html

    - name: Run acceptance tests with tavern
      run: |
        export CONFIG_HOST=config.${MINIKUBE_IP}.nip.io
        export MOCK_HOST=mock.${MINIKUBE_IP}.nip.io
        py.test -vv --html=./test/tavern/report.html --self-contained-html ./test/tavern/test.tavern.yaml


