name: OnPR

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./scripts/go-build.sh 

    - name: Test
      run: go test -coverprofile cover.out ./...

    - name: Cover output
      run: go tool cover -func=cover.out

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/Dockerfile
        push: false
        tags: alitari/mockgo-server:latest
