name: OnPR

on:
  pull_request:
    branches: [ "master" ]

jobs:

  golang-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./scripts/go-build.sh 

    - name: Test
      run: go test -coverprofile cover.out ./...

    - name: Cover output
      run: go tool cover -func=cover.out

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/docker/Dockerfile
        push: false
        tags: alitari/mockgo-server:latest

  skaffold-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Start Minikube
      id: minikube
      uses: hiberbee/github-action-minikube@1.7.0
      with:
        addons: ingress
    - name: Get Minikube IP
      run: echo "MINIKUBE_IP=${{ steps.minikube.outputs.ip }}" >> $GITHUB_ENV
    - name: Get cluster info
      run: kubectl cluster-info

    - name: Run Skaffold
      uses: hiberbee/github-action-skaffold@1.22.0
      with:
        command: run
    - name: Get Helm releases
      run: helm list
    - name: Show k8s resources
      run: kubectl get pod,service,statefulset,configmap,secret,ingress
    - name: Integration test precheck
      run: ./scripts/integration-test-precheck.sh