name: Workflow

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  golang-builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'

    - name: install tools
      run: |
        sudo apt update -y
        sudo apt install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/client9/misspell/cmd/misspell@latest
        go install github.com/gordonklaus/ineffassign@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
        curl -silent --location https://github.com/Orange-OpenSource/hurl/releases/download/2.0.1/hurl-2.0.1-x86_64-linux.tar.gz | tar xvz -C ${HOME}/bin
        export PATH=${HOME}/bin/hurl-2.0.1:$PATH

    - name: check tools
      run: make env 

